Repository cisagov/LME, pull requests merged in 2023-12, with the labels that each got.

#86 Upgrade ELK stack to 8.11.1
  Chapter 3 Files/dashboard_update.sh
  Chapter 3 Files/deploy.sh
  Chapter 3 Files/docker-compose-stack.yml
Labels: improvement, version bump

#93 Added instructions to update from Release 1.1.0 to Release 1.2.0 to u…
  docs/markdown/maintenance/upgrading.md
Labels: documentation

#101 Release 1.2.0 MERGE INTO MAIN
  Chapter 3 Files/dashboard_update.sh
  Chapter 3 Files/deploy.sh
  Chapter 3 Files/docker-compose-stack.yml
  docs/markdown/maintenance/upgrading.md
Labels: improvement

#105 Create gitattributes file
  .gitattributes
Labels: improvement

#107 Remove elastic user password prompt from deploy.sh
  Chapter 3 Files/deploy.sh
Labels: bug

#91 Release 1.3.0 MERGE TO MAIN
  .gitattributes
  .github/workflows/main.yml
  CONTRIBUTING.md
  Chapter 3 Files/dashboard_update.sh
  Chapter 3 Files/deploy.sh
  Chapter 4 Files/dashboards/Healthcheckoverview_dashboard.ndjson
  Chapter 4 Files/dashboards/alerting_dashboard.ndjson
  Chapter 4 Files/dashboards/process_explorer.ndjson
  Chapter 4 Files/dashboards/security_dashboard_security_log.ndjson
  Chapter 4 Files/dashboards/sysmon_summary.ndjson
  Chapter 4 Files/dashboards/user_security.ndjson
  docs/markdown/chapter3/chapter3.md
  docs/markdown/maintenance/upgrading.md
  docs/markdown/reference/troubleshooting.md
Labels: improvement

#138 Add a markdown file for dashboard descriptions, link new file in README.md
  README.md
  docs/markdown/reference/dashboard-descriptions.md
Labels: documentation
