Repository cisagov/LME, pull requests merged in 2023-11, with the labels that each got.

#26 Remove screenshot column
  docs/imgs/testing-screenshots/delete.png
  docs/imgs/testing-screenshots/shell.png
  docs/imgs/testing-screenshots/shell2.png
  docs/imgs/testing-screenshots/shell3.png
  docs/imgs/testing-screenshots/shell4.png
  docs/imgs/testing-screenshots/shell5.png
  testing/Readme.md
Labels: documentation

#36 Export dashboards
  .gitignore
  Chapter 4 Files/dashboards/Readme.md
  Chapter 4 Files/export_dashboards.py
  Chapter 4 Files/requirements.txt
  testing/SetupTestbed.ps1
Labels: improvement

#44 Bump Elasticsearch version
  Chapter 3 Files/docker-compose-stack.yml
  docs/markdown/maintenance/upgrading.md
Labels: improvement

#37 Update process explorer dashboard
  Chapter 4 Files/dashboards/process_explorer.ndjson
Labels: improvement

#51 Add Computer Software Overview dashboard
  Chapter 4 Files/dashboards/computer_software_overview.ndjson
Labels: improvement

#54 Readme updates for dashboards
  Chapter 4 Files/dashboards/Readme.md
  docs/markdown/maintenance/upgrading.md
Labels: improvement

#61 Release 1.1.0 small updates
  Chapter 3 Files/deploy.sh
  docs/markdown/prerequisites.md
Labels: bug

#60 Release 1.1.0 small
  .github/ISSUE_TEMPLATE/bug-or-error-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  CONTRIBUTING.md
  Chapter 3 Files/.gitignore
  Chapter 3 Files/deploy.sh
  Chapter 4 Files/dashboards/Readme.md
  Chapter 4 Files/dashboards/alerting_dashboard.ndjson
  Chapter 4 Files/dashboards/computer_software_overview.ndjson
  Chapter 4 Files/dashboards/process_explorer.ndjson
  Chapter 4 Files/dashboards/security_dashboard_home.ndjson
  Chapter 4 Files/dashboards/security_dashboard_security_log.ndjson
  Chapter 4 Files/dashboards/sysmon_summary.ndjson
  Chapter 4 Files/dashboards/user_hr.ndjson
  Chapter 4 Files/dashboards/user_security.ndjson
  Chapter 4 Files/export_dashboards.py
  Chapter 4 Files/requirements.txt
  RELEASES.md
  docs/markdown/chapter4.md
  docs/markdown/logging-guidance/filtering.md
  docs/markdown/prerequisites.md
  docs/markdown/reference/troubleshooting.md
  testing/SetupTestbed.ps1
Labels: documentation, improvement, code freeze

#64 Increase max_attempts value in deploy.sh
  Chapter 3 Files/deploy.sh
Labels: bug

#76 Enhance dashboard update instructions
  Chapter 4 Files/dashboards/Readme.md
  docs/markdown/chapter4.md
  docs/markdown/maintenance/upgrading.md
Labels: documentation

#75 Remove alerting dashboard from menu
  Chapter 4 Files/dashboards/alerting_dashboard.ndjson
  Chapter 4 Files/dashboards/computer_software_overview.ndjson
  Chapter 4 Files/dashboards/process_explorer.ndjson
  Chapter 4 Files/dashboards/security_dashboard_security_log.ndjson
  Chapter 4 Files/dashboards/sysmon_summary.ndjson
  Chapter 4 Files/dashboards/user_hr.ndjson
  Chapter 4 Files/dashboards/user_security.ndjson
  Chapter 4 Files/export_dashboards.py
Labels: bug, improvement
