Repository cisagov/LME, pull requests merged in 2024-03, with the labels that each got.

#183 Python testbed setup
  .devcontainer/python_development/devcontainer.json
  .devcontainer/python_tests/devcontainer.json
  .github/workflows/cluster.yml
  .github/workflows/linux_only.yml
  .gitignore
  Chapter 3 Files/deploy.sh
  testing/configure/linux_install_lme.exp
  testing/development/Dockerfile
  testing/development/build_docker_lme_install.sh
  testing/development/docker-compose.yml
  testing/tests/.env_example
  testing/tests/.vscode/launch.json
  testing/tests/.vscode/settings.json
  testing/tests/Dockerfile
  testing/tests/README.md
  testing/tests/api_tests/__init__.py
  testing/tests/api_tests/helpers.py
  testing/tests/api_tests/linux_only/__init__.py
  testing/tests/api_tests/linux_only/conftest.py
  testing/tests/api_tests/linux_only/schemas/es_root.json
  testing/tests/api_tests/linux_only/test_data/response.json
  testing/tests/api_tests/linux_only/test_server.py
  testing/tests/api_tests/winlogbeat/__init__.py
  testing/tests/api_tests/winlogbeat/conftest.py
  testing/tests/api_tests/winlogbeat/schemas/winlogbeat_search.json
  testing/tests/api_tests/winlogbeat/test_data/mapping_datafields.txt
  testing/tests/api_tests/winlogbeat/test_data/mapping_response.json
  testing/tests/api_tests/winlogbeat/test_data/mapping_response_actual.json
  testing/tests/api_tests/winlogbeat/test_data/winlog_search_data.json
  testing/tests/api_tests/winlogbeat/test_server.py
  testing/tests/docker-compose.yml
  testing/tests/requirements.txt
Labels: improvement

#199 Create new workflow for automating the release process
  .github/changelog-configuration.json
  .github/workflows/build_release.yaml
  .github/workflows/main.yml
Labels: improvement, feat

#223 Update and rename replica function to current elastic standards
  Chapter 3 Files/deploy.sh
Labels: bug
