Repository cisagov/LME, pull requests merged in 2024-01, with the labels that each got.

#136 Updated PR template and CONTRIBUTING.md to include new conventions for formatting and labeling PR's
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, improvement

#134 Updated troubleshooting guide to account for index management
  docs/markdown/reference/troubleshooting.md
Labels: documentation

#154 Release 1.3.1 merge into main
  Chapter 3 Files/deploy.sh
  docs/markdown/maintenance/upgrading.md
  docs/markdown/reference/troubleshooting.md
Labels: bug, documentation

#167 Fixes dashboard update not importing on fresh install
  Chapter 3 Files/dashboard_update.sh
  Chapter 3 Files/deploy.sh
  docs/markdown/maintenance/upgrading.md
Labels: bug

#169 Release 1.3.2 merge into main
  Chapter 3 Files/dashboard_update.sh
  Chapter 3 Files/deploy.sh
  docs/markdown/maintenance/upgrading.md
Labels: bug, documentation
